// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: optimized/proto/gateway_optimized.proto

package optimizedpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OptimizedEdgeGatewayService_PublishTelemetry_FullMethodName      = "/gateway.optimized.v1.OptimizedEdgeGatewayService/PublishTelemetry"
	OptimizedEdgeGatewayService_PublishBatchTelemetry_FullMethodName = "/gateway.optimized.v1.OptimizedEdgeGatewayService/PublishBatchTelemetry"
	OptimizedEdgeGatewayService_StreamTelemetry_FullMethodName       = "/gateway.optimized.v1.OptimizedEdgeGatewayService/StreamTelemetry"
	OptimizedEdgeGatewayService_HealthCheck_FullMethodName           = "/gateway.optimized.v1.OptimizedEdgeGatewayService/HealthCheck"
)

// OptimizedEdgeGatewayServiceClient is the client API for OptimizedEdgeGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 优化版 IoT 边缘网关 gRPC 接口
type OptimizedEdgeGatewayServiceClient interface {
	// 单次上报（兼容简单场景）
	PublishTelemetry(ctx context.Context, in *Telemetry, opts ...grpc.CallOption) (*TelemetryAck, error)
	// 批量上报（多条样本合并）
	PublishBatchTelemetry(ctx context.Context, in *BatchTelemetry, opts ...grpc.CallOption) (*TelemetryAck, error)
	// 流式上报（客户端流，长连接持续上报）
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Telemetry, StreamAck], error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type optimizedEdgeGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizedEdgeGatewayServiceClient(cc grpc.ClientConnInterface) OptimizedEdgeGatewayServiceClient {
	return &optimizedEdgeGatewayServiceClient{cc}
}

func (c *optimizedEdgeGatewayServiceClient) PublishTelemetry(ctx context.Context, in *Telemetry, opts ...grpc.CallOption) (*TelemetryAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryAck)
	err := c.cc.Invoke(ctx, OptimizedEdgeGatewayService_PublishTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizedEdgeGatewayServiceClient) PublishBatchTelemetry(ctx context.Context, in *BatchTelemetry, opts ...grpc.CallOption) (*TelemetryAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryAck)
	err := c.cc.Invoke(ctx, OptimizedEdgeGatewayService_PublishBatchTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizedEdgeGatewayServiceClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Telemetry, StreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OptimizedEdgeGatewayService_ServiceDesc.Streams[0], OptimizedEdgeGatewayService_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Telemetry, StreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OptimizedEdgeGatewayService_StreamTelemetryClient = grpc.ClientStreamingClient[Telemetry, StreamAck]

func (c *optimizedEdgeGatewayServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, OptimizedEdgeGatewayService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizedEdgeGatewayServiceServer is the server API for OptimizedEdgeGatewayService service.
// All implementations must embed UnimplementedOptimizedEdgeGatewayServiceServer
// for forward compatibility.
//
// 优化版 IoT 边缘网关 gRPC 接口
type OptimizedEdgeGatewayServiceServer interface {
	// 单次上报（兼容简单场景）
	PublishTelemetry(context.Context, *Telemetry) (*TelemetryAck, error)
	// 批量上报（多条样本合并）
	PublishBatchTelemetry(context.Context, *BatchTelemetry) (*TelemetryAck, error)
	// 流式上报（客户端流，长连接持续上报）
	StreamTelemetry(grpc.ClientStreamingServer[Telemetry, StreamAck]) error
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedOptimizedEdgeGatewayServiceServer()
}

// UnimplementedOptimizedEdgeGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizedEdgeGatewayServiceServer struct{}

func (UnimplementedOptimizedEdgeGatewayServiceServer) PublishTelemetry(context.Context, *Telemetry) (*TelemetryAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTelemetry not implemented")
}
func (UnimplementedOptimizedEdgeGatewayServiceServer) PublishBatchTelemetry(context.Context, *BatchTelemetry) (*TelemetryAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishBatchTelemetry not implemented")
}
func (UnimplementedOptimizedEdgeGatewayServiceServer) StreamTelemetry(grpc.ClientStreamingServer[Telemetry, StreamAck]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedOptimizedEdgeGatewayServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedOptimizedEdgeGatewayServiceServer) mustEmbedUnimplementedOptimizedEdgeGatewayServiceServer() {
}
func (UnimplementedOptimizedEdgeGatewayServiceServer) testEmbeddedByValue() {}

// UnsafeOptimizedEdgeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizedEdgeGatewayServiceServer will
// result in compilation errors.
type UnsafeOptimizedEdgeGatewayServiceServer interface {
	mustEmbedUnimplementedOptimizedEdgeGatewayServiceServer()
}

func RegisterOptimizedEdgeGatewayServiceServer(s grpc.ServiceRegistrar, srv OptimizedEdgeGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedOptimizedEdgeGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OptimizedEdgeGatewayService_ServiceDesc, srv)
}

func _OptimizedEdgeGatewayService_PublishTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Telemetry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizedEdgeGatewayServiceServer).PublishTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizedEdgeGatewayService_PublishTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizedEdgeGatewayServiceServer).PublishTelemetry(ctx, req.(*Telemetry))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizedEdgeGatewayService_PublishBatchTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchTelemetry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizedEdgeGatewayServiceServer).PublishBatchTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizedEdgeGatewayService_PublishBatchTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizedEdgeGatewayServiceServer).PublishBatchTelemetry(ctx, req.(*BatchTelemetry))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizedEdgeGatewayService_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OptimizedEdgeGatewayServiceServer).StreamTelemetry(&grpc.GenericServerStream[Telemetry, StreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OptimizedEdgeGatewayService_StreamTelemetryServer = grpc.ClientStreamingServer[Telemetry, StreamAck]

func _OptimizedEdgeGatewayService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizedEdgeGatewayServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizedEdgeGatewayService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizedEdgeGatewayServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OptimizedEdgeGatewayService_ServiceDesc is the grpc.ServiceDesc for OptimizedEdgeGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptimizedEdgeGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.optimized.v1.OptimizedEdgeGatewayService",
	HandlerType: (*OptimizedEdgeGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishTelemetry",
			Handler:    _OptimizedEdgeGatewayService_PublishTelemetry_Handler,
		},
		{
			MethodName: "PublishBatchTelemetry",
			Handler:    _OptimizedEdgeGatewayService_PublishBatchTelemetry_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _OptimizedEdgeGatewayService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _OptimizedEdgeGatewayService_StreamTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "optimized/proto/gateway_optimized.proto",
}
