// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: optimized/proto/gateway_optimized.proto

package optimizedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 紧凑的指标结构（替代 map<string, double>）
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        // 预定义 ID: 1=temp, 2=humidity, 100+=vibration
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"` // 用 float 替代 double，省一半空间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_optimized_proto_gateway_optimized_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Metric) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 单条遥测样本（用于批量上报）
type TelemetrySample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetrySample) Reset() {
	*x = TelemetrySample{}
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySample) ProtoMessage() {}

func (x *TelemetrySample) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySample.ProtoReflect.Descriptor instead.
func (*TelemetrySample) Descriptor() ([]byte, []int) {
	return file_optimized_proto_gateway_optimized_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetrySample) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TelemetrySample) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 单条遥测消息（用于流式和单次上报）
type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	ClientAvg     float64                `protobuf:"fixed64,4,opt,name=client_avg,json=clientAvg,proto3" json:"client_avg,omitempty"`
	Priority      uint32                 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"` // 0=背景流量, 1=列车实时流量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_optimized_proto_gateway_optimized_proto_rawDescGZIP(), []int{2}
}

func (x *Telemetry) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Telemetry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Telemetry) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Telemetry) GetClientAvg() float64 {
	if x != nil {
		return x.ClientAvg
	}
	return 0
}

func (x *Telemetry) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// 批量遥测消息
type BatchTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Samples       []*TelemetrySample     `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	ClientAvg     float64                `protobuf:"fixed64,3,opt,name=client_avg,json=clientAvg,proto3" json:"client_avg,omitempty"`
	Priority      uint32                 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTelemetry) Reset() {
	*x = BatchTelemetry{}
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTelemetry) ProtoMessage() {}

func (x *BatchTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTelemetry.ProtoReflect.Descriptor instead.
func (*BatchTelemetry) Descriptor() ([]byte, []int) {
	return file_optimized_proto_gateway_optimized_proto_rawDescGZIP(), []int{3}
}

func (x *BatchTelemetry) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *BatchTelemetry) GetSamples() []*TelemetrySample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *BatchTelemetry) GetClientAvg() float64 {
	if x != nil {
		return x.ClientAvg
	}
	return 0
}

func (x *BatchTelemetry) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// 遥测响应
type TelemetryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServerAvg     float64                `protobuf:"fixed64,3,opt,name=server_avg,json=serverAvg,proto3" json:"server_avg,omitempty"`
	ClientAvg     float64                `protobuf:"fixed64,4,opt,name=client_avg,json=clientAvg,proto3" json:"client_avg,omitempty"`
	Diff          float64                `protobuf:"fixed64,5,opt,name=diff,proto3" json:"diff,omitempty"`
	Verified      bool                   `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	ReceivedCount uint64                 `protobuf:"varint,7,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"` // 收到的样本数（用于批量/流式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_optimized_proto_gateway_optimized_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TelemetryAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TelemetryAck) GetServerAvg() float64 {
	if x != nil {
		return x.ServerAvg
	}
	return 0
}

func (x *TelemetryAck) GetClientAvg() float64 {
	if x != nil {
		return x.ClientAvg
	}
	return 0
}

func (x *TelemetryAck) GetDiff() float64 {
	if x != nil {
		return x.Diff
	}
	return 0
}

func (x *TelemetryAck) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *TelemetryAck) GetReceivedCount() uint64 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

// 流式上报的最终响应
type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedCount uint64                 `protobuf:"varint,1,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ServerAvg     float64                `protobuf:"fixed64,3,opt,name=server_avg,json=serverAvg,proto3" json:"server_avg,omitempty"`
	Verified      bool                   `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_optimized_proto_gateway_optimized_proto_rawDescGZIP(), []int{5}
}

func (x *StreamAck) GetReceivedCount() uint64 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

func (x *StreamAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StreamAck) GetServerAvg() float64 {
	if x != nil {
		return x.ServerAvg
	}
	return 0
}

func (x *StreamAck) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

// 健康检查
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_optimized_proto_gateway_optimized_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthCheckResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Status               string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	HighPriorityQueueLen uint64                 `protobuf:"varint,2,opt,name=high_priority_queue_len,json=highPriorityQueueLen,proto3" json:"high_priority_queue_len,omitempty"`
	LowPriorityQueueLen  uint64                 `protobuf:"varint,3,opt,name=low_priority_queue_len,json=lowPriorityQueueLen,proto3" json:"low_priority_queue_len,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimized_proto_gateway_optimized_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_optimized_proto_gateway_optimized_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetHighPriorityQueueLen() uint64 {
	if x != nil {
		return x.HighPriorityQueueLen
	}
	return 0
}

func (x *HealthCheckResponse) GetLowPriorityQueueLen() uint64 {
	if x != nil {
		return x.LowPriorityQueueLen
	}
	return 0
}

var File_optimized_proto_gateway_optimized_proto protoreflect.FileDescriptor

const file_optimized_proto_gateway_optimized_proto_rawDesc = "" +
	"\n" +
	"'optimized/proto/gateway_optimized.proto\x12\x14gateway.optimized.v1\".\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"l\n" +
	"\x0fTelemetrySample\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x126\n" +
	"\ametrics\x18\x02 \x03(\v2\x1c.gateway.optimized.v1.MetricR\ametrics\"\xbe\x01\n" +
	"\tTelemetry\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x126\n" +
	"\ametrics\x18\x03 \x03(\v2\x1c.gateway.optimized.v1.MetricR\ametrics\x12\x1d\n" +
	"\n" +
	"client_avg\x18\x04 \x01(\x01R\tclientAvg\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\"\xa9\x01\n" +
	"\x0eBatchTelemetry\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12?\n" +
	"\asamples\x18\x02 \x03(\v2%.gateway.optimized.v1.TelemetrySampleR\asamples\x12\x1d\n" +
	"\n" +
	"client_avg\x18\x03 \x01(\x01R\tclientAvg\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\rR\bpriority\"\xd5\x01\n" +
	"\fTelemetryAck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"server_avg\x18\x03 \x01(\x01R\tserverAvg\x12\x1d\n" +
	"\n" +
	"client_avg\x18\x04 \x01(\x01R\tclientAvg\x12\x12\n" +
	"\x04diff\x18\x05 \x01(\x01R\x04diff\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x12%\n" +
	"\x0ereceived_count\x18\a \x01(\x04R\rreceivedCount\"\x85\x01\n" +
	"\tStreamAck\x12%\n" +
	"\x0ereceived_count\x18\x01 \x01(\x04R\rreceivedCount\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"server_avg\x18\x03 \x01(\x01R\tserverAvg\x12\x1a\n" +
	"\bverified\x18\x04 \x01(\bR\bverified\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x99\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x125\n" +
	"\x17high_priority_queue_len\x18\x02 \x01(\x04R\x14highPriorityQueueLen\x123\n" +
	"\x16low_priority_queue_len\x18\x03 \x01(\x04R\x13lowPriorityQueueLen2\x94\x03\n" +
	"\x1bOptimizedEdgeGatewayService\x12W\n" +
	"\x10PublishTelemetry\x12\x1f.gateway.optimized.v1.Telemetry\x1a\".gateway.optimized.v1.TelemetryAck\x12a\n" +
	"\x15PublishBatchTelemetry\x12$.gateway.optimized.v1.BatchTelemetry\x1a\".gateway.optimized.v1.TelemetryAck\x12U\n" +
	"\x0fStreamTelemetry\x12\x1f.gateway.optimized.v1.Telemetry\x1a\x1f.gateway.optimized.v1.StreamAck(\x01\x12b\n" +
	"\vHealthCheck\x12(.gateway.optimized.v1.HealthCheckRequest\x1a).gateway.optimized.v1.HealthCheckResponseB!Z\x1fiot/optimized/proto;optimizedpbb\x06proto3"

var (
	file_optimized_proto_gateway_optimized_proto_rawDescOnce sync.Once
	file_optimized_proto_gateway_optimized_proto_rawDescData []byte
)

func file_optimized_proto_gateway_optimized_proto_rawDescGZIP() []byte {
	file_optimized_proto_gateway_optimized_proto_rawDescOnce.Do(func() {
		file_optimized_proto_gateway_optimized_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimized_proto_gateway_optimized_proto_rawDesc), len(file_optimized_proto_gateway_optimized_proto_rawDesc)))
	})
	return file_optimized_proto_gateway_optimized_proto_rawDescData
}

var file_optimized_proto_gateway_optimized_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_optimized_proto_gateway_optimized_proto_goTypes = []any{
	(*Metric)(nil),              // 0: gateway.optimized.v1.Metric
	(*TelemetrySample)(nil),     // 1: gateway.optimized.v1.TelemetrySample
	(*Telemetry)(nil),           // 2: gateway.optimized.v1.Telemetry
	(*BatchTelemetry)(nil),      // 3: gateway.optimized.v1.BatchTelemetry
	(*TelemetryAck)(nil),        // 4: gateway.optimized.v1.TelemetryAck
	(*StreamAck)(nil),           // 5: gateway.optimized.v1.StreamAck
	(*HealthCheckRequest)(nil),  // 6: gateway.optimized.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 7: gateway.optimized.v1.HealthCheckResponse
}
var file_optimized_proto_gateway_optimized_proto_depIdxs = []int32{
	0, // 0: gateway.optimized.v1.TelemetrySample.metrics:type_name -> gateway.optimized.v1.Metric
	0, // 1: gateway.optimized.v1.Telemetry.metrics:type_name -> gateway.optimized.v1.Metric
	1, // 2: gateway.optimized.v1.BatchTelemetry.samples:type_name -> gateway.optimized.v1.TelemetrySample
	2, // 3: gateway.optimized.v1.OptimizedEdgeGatewayService.PublishTelemetry:input_type -> gateway.optimized.v1.Telemetry
	3, // 4: gateway.optimized.v1.OptimizedEdgeGatewayService.PublishBatchTelemetry:input_type -> gateway.optimized.v1.BatchTelemetry
	2, // 5: gateway.optimized.v1.OptimizedEdgeGatewayService.StreamTelemetry:input_type -> gateway.optimized.v1.Telemetry
	6, // 6: gateway.optimized.v1.OptimizedEdgeGatewayService.HealthCheck:input_type -> gateway.optimized.v1.HealthCheckRequest
	4, // 7: gateway.optimized.v1.OptimizedEdgeGatewayService.PublishTelemetry:output_type -> gateway.optimized.v1.TelemetryAck
	4, // 8: gateway.optimized.v1.OptimizedEdgeGatewayService.PublishBatchTelemetry:output_type -> gateway.optimized.v1.TelemetryAck
	5, // 9: gateway.optimized.v1.OptimizedEdgeGatewayService.StreamTelemetry:output_type -> gateway.optimized.v1.StreamAck
	7, // 10: gateway.optimized.v1.OptimizedEdgeGatewayService.HealthCheck:output_type -> gateway.optimized.v1.HealthCheckResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_optimized_proto_gateway_optimized_proto_init() }
func file_optimized_proto_gateway_optimized_proto_init() {
	if File_optimized_proto_gateway_optimized_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimized_proto_gateway_optimized_proto_rawDesc), len(file_optimized_proto_gateway_optimized_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optimized_proto_gateway_optimized_proto_goTypes,
		DependencyIndexes: file_optimized_proto_gateway_optimized_proto_depIdxs,
		MessageInfos:      file_optimized_proto_gateway_optimized_proto_msgTypes,
	}.Build()
	File_optimized_proto_gateway_optimized_proto = out.File
	file_optimized_proto_gateway_optimized_proto_goTypes = nil
	file_optimized_proto_gateway_optimized_proto_depIdxs = nil
}
