// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EdgeGatewayService_PublishTelemetry_FullMethodName = "/gateway.v1.EdgeGatewayService/PublishTelemetry"
	EdgeGatewayService_HealthCheck_FullMethodName      = "/gateway.v1.EdgeGatewayService/HealthCheck"
)

// EdgeGatewayServiceClient is the client API for EdgeGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IoT 边缘网关 gRPC 接口
type EdgeGatewayServiceClient interface {
	// 设备上报遥测数据（Unary）
	PublishTelemetry(ctx context.Context, in *Telemetry, opts ...grpc.CallOption) (*TelemetryAck, error)
	// 网关健康检查（Unary）
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type edgeGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeGatewayServiceClient(cc grpc.ClientConnInterface) EdgeGatewayServiceClient {
	return &edgeGatewayServiceClient{cc}
}

func (c *edgeGatewayServiceClient) PublishTelemetry(ctx context.Context, in *Telemetry, opts ...grpc.CallOption) (*TelemetryAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryAck)
	err := c.cc.Invoke(ctx, EdgeGatewayService_PublishTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeGatewayServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, EdgeGatewayService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeGatewayServiceServer is the server API for EdgeGatewayService service.
// All implementations must embed UnimplementedEdgeGatewayServiceServer
// for forward compatibility.
//
// IoT 边缘网关 gRPC 接口
type EdgeGatewayServiceServer interface {
	// 设备上报遥测数据（Unary）
	PublishTelemetry(context.Context, *Telemetry) (*TelemetryAck, error)
	// 网关健康检查（Unary）
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedEdgeGatewayServiceServer()
}

// UnimplementedEdgeGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeGatewayServiceServer struct{}

func (UnimplementedEdgeGatewayServiceServer) PublishTelemetry(context.Context, *Telemetry) (*TelemetryAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTelemetry not implemented")
}
func (UnimplementedEdgeGatewayServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedEdgeGatewayServiceServer) mustEmbedUnimplementedEdgeGatewayServiceServer() {}
func (UnimplementedEdgeGatewayServiceServer) testEmbeddedByValue()                            {}

// UnsafeEdgeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeGatewayServiceServer will
// result in compilation errors.
type UnsafeEdgeGatewayServiceServer interface {
	mustEmbedUnimplementedEdgeGatewayServiceServer()
}

func RegisterEdgeGatewayServiceServer(s grpc.ServiceRegistrar, srv EdgeGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedEdgeGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdgeGatewayService_ServiceDesc, srv)
}

func _EdgeGatewayService_PublishTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Telemetry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeGatewayServiceServer).PublishTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeGatewayService_PublishTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeGatewayServiceServer).PublishTelemetry(ctx, req.(*Telemetry))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeGatewayService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeGatewayServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeGatewayService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeGatewayServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EdgeGatewayService_ServiceDesc is the grpc.ServiceDesc for EdgeGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.EdgeGatewayService",
	HandlerType: (*EdgeGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishTelemetry",
			Handler:    _EdgeGatewayService_PublishTelemetry_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _EdgeGatewayService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gateway.proto",
}
