// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 基础遥测上报消息
type Telemetry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DeviceId    string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                                           // 设备 ID
	TimestampMs int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`                                                 // 时间戳（毫秒）
	Metrics     map[string]float64     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // 指标名称 -> 数值
	// 客户端本地计算的平均值
	ClientAvg     float64 `protobuf:"fixed64,4,opt,name=client_avg,json=clientAvg,proto3" json:"client_avg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Telemetry) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Telemetry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Telemetry) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Telemetry) GetClientAvg() float64 {
	if x != nil {
		return x.ClientAvg
	}
	return 0
}

// 遥测上报响应
type TelemetryAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // 简单状态，如 "OK"
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 可选说明
	// 服务端计算的平均值
	ServerAvg float64 `protobuf:"fixed64,3,opt,name=server_avg,json=serverAvg,proto3" json:"server_avg,omitempty"`
	// 回显客户端平均值
	ClientAvg float64 `protobuf:"fixed64,4,opt,name=client_avg,json=clientAvg,proto3" json:"client_avg,omitempty"`
	// 差值
	Diff float64 `protobuf:"fixed64,5,opt,name=diff,proto3" json:"diff,omitempty"`
	// 是否在误差范围内
	Verified      bool `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TelemetryAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TelemetryAck) GetServerAvg() float64 {
	if x != nil {
		return x.ServerAvg
	}
	return 0
}

func (x *TelemetryAck) GetClientAvg() float64 {
	if x != nil {
		return x.ClientAvg
	}
	return 0
}

func (x *TelemetryAck) GetDiff() float64 {
	if x != nil {
		return x.Diff
	}
	return 0
}

func (x *TelemetryAck) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

// 简单健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\n" +
	"gateway.v1\"\xe4\x01\n" +
	"\tTelemetry\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12<\n" +
	"\ametrics\x18\x03 \x03(\v2\".gateway.v1.Telemetry.MetricsEntryR\ametrics\x12\x1d\n" +
	"\n" +
	"client_avg\x18\x04 \x01(\x01R\tclientAvg\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xae\x01\n" +
	"\fTelemetryAck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"server_avg\x18\x03 \x01(\x01R\tserverAvg\x12\x1d\n" +
	"\n" +
	"client_avg\x18\x04 \x01(\x01R\tclientAvg\x12\x12\n" +
	"\x04diff\x18\x05 \x01(\x01R\x04diff\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xa9\x01\n" +
	"\x12EdgeGatewayService\x12C\n" +
	"\x10PublishTelemetry\x12\x15.gateway.v1.Telemetry\x1a\x18.gateway.v1.TelemetryAck\x12N\n" +
	"\vHealthCheck\x12\x1e.gateway.v1.HealthCheckRequest\x1a\x1f.gateway.v1.HealthCheckResponseB\x15Z\x13iot/proto;gatewaypbb\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_gateway_proto_goTypes = []any{
	(*Telemetry)(nil),           // 0: gateway.v1.Telemetry
	(*TelemetryAck)(nil),        // 1: gateway.v1.TelemetryAck
	(*HealthCheckRequest)(nil),  // 2: gateway.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: gateway.v1.HealthCheckResponse
	nil,                         // 4: gateway.v1.Telemetry.MetricsEntry
}
var file_proto_gateway_proto_depIdxs = []int32{
	4, // 0: gateway.v1.Telemetry.metrics:type_name -> gateway.v1.Telemetry.MetricsEntry
	0, // 1: gateway.v1.EdgeGatewayService.PublishTelemetry:input_type -> gateway.v1.Telemetry
	2, // 2: gateway.v1.EdgeGatewayService.HealthCheck:input_type -> gateway.v1.HealthCheckRequest
	1, // 3: gateway.v1.EdgeGatewayService.PublishTelemetry:output_type -> gateway.v1.TelemetryAck
	3, // 4: gateway.v1.EdgeGatewayService.HealthCheck:output_type -> gateway.v1.HealthCheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
